# Generated by Django 6.0.2 on 2026-05-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_tag_product_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="tag",
            new_name="tags",
        ),
    ]
